### ISSUE TITLE
Support loading configuration defaults from file

### ISSUE THREAD

**Issue by mjballard** [p0pr0ck5/lua-resty-waf#108]
In the future it may be nice to support a configuration file of sorts that contains all of the blacklisted/whitelisted IPs and other configurable that are set in *_by_lua sections.

**Comment by p0pr0ck5** [comment]
Given that we'll be loading rules from JSON files, we should be able to tackle this as well. `init` phase work can have some blocking IO done by the master process, so we'll be safe here.

**Comment by p0pr0ck5** [comment]
Meh. Anyone who's deploying this at any scale will have an automated method to deploy nginx configs. Adding this is just another layer of complexity.
