### ISSUE TITLE
Support adding rulesets via JSON string

### ISSUE THREAD

**Issue by p0pr0ck5** [p0pr0ck5/lua-resty-waf#130]
This would make testing much easier as we can write arbitrary rulesets without having to add them to the included directory.

* testing skips
* testing var modifiers like length

**Comment by hy05190134** [comment]
it seems that you are so active nowadays, rather than so busy before. Have you graduated from school?

**Comment by p0pr0ck5** [comment]
I graduated from school several years ago. Last year I was busy with personal matters. My employer has is sponsoring some development of FreeWAF so I have more time to work on this outside of my personal life.

Also, this is not the appropriate place for this conversation. Feel free to send me an email directory (robert@cryptobells.com) or join the #freewaf IRC channel,.

**Comment by p0pr0ck5** [comment]
Meh, I don't really see any value in this. It's weird- we'd already be asking someone to run modsec2lua-resty-waf.
