### ISSUE TITLE
Can not ignore the rule if it's the last rule in ruleset.

### ISSUE THREAD

**Issue by emrahcom** [p0pr0ck5/lua-resty-waf#137]
Hi Robert,

I can reproduce the bug when I ignore the rule 42097 (which is the last rule in 42000 ruleset) and the 41035 (which is the last rule in 41000 ruleset). I get "500 Internal Server Error" in my browser.

I'm working with the current master branch of lua-resty-waf. My box is Debian Jessie with Nginx from the Debian repo. "PCRE optimization" is disabled and it works well if I don't ignore a last rule from a ruleset. I didn't test the issue with openresty.

# error.log
2016/04/04 15:41:08 [error] 2501#0: *6 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/lua-resty-waf/waf.lua:470: attempt to perform arithmetic on field 'offset_nomatch' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/lua-resty-waf/waf.lua: in function 'exec'
        access_by_lua:9: in function <access_by_lua:1>, client: 10.10.18.170, server: _, request: "GET /tr/main/pages/proje-hakkinda/6 HTTP/1.1", host: "10.10.18.80"

# /etc/nginx/conf.d/waf.conf
lua_package_path '/usr/local/share/lua/5.1/lua-resty-waf/?.lua;;';
lua_package_cpath '/usr/local/share/lua/5.1/lua-resty-waf/?.lua;;';

init_by_lua '
        local lua_resty_waf = require "waf"

        lua_resty_waf.default_option("mode", "ACTIVE")
        lua_resty_waf.default_option("disable_pcre_optimization", true)
        lua_resty_waf.default_option("score_threshold", 5)

        lua_resty_waf.default_option("event_log_target", "file")
        lua_resty_waf.default_option("event_log_target_path", "/var/log/nginx/waf.log")
        lua_resty_waf.default_option("event_log_buffer_size", 8192)
        lua_resty_waf.default_option("event_log_verbosity", 3)
        lua_resty_waf.default_option("event_log_periodic_flush", 60)
        lua_resty_waf.default_option("event_log_ngx_vars", "host")
        lua_resty_waf.default_option("debug", true)
        lua_resty_waf.default_option("debug_log_level", ngx.WARN)

        lua_resty_waf.init()
';

# /etc/nginx/sites-enabled/default
server {
access_by_lua '
        local lua_resty_waf = require "waf"
        local waf = lua_resty_waf:new()
        waf:set_option("ignore_rule", 40002)
        waf:set_option("ignore_rule", 41014)
        waf:set_option("ignore_rule", 41015)
        waf:set_option("ignore_rule", 42097)
        -- waf:set_option("ignore_rule", 41035)
        waf:exec()
';
header_filter_by_lua '
        local lua_resty_waf = require "waf"
        local waf = lua_resty_waf:new()
        waf:exec()
';
body_filter_by_lua '
        local lua_resty_waf = require "waf"
        local waf = lua_resty_waf:new()
        waf:exec()
';
log_by_lua '
        local lua_resty_waf = require "waf"
        local waf = lua_resty_waf:new()
        waf:write_log_events()
';

...
...

**Comment by p0pr0ck5** [comment]
Thanks for the thorough report :) I know where the bug lies and I will have a patch on the development branch tomorrow.

**Comment by p0pr0ck5** [comment]
I've added a patch to the development branch that fixes this. I won't have time to test until tomorrow, can you let me know if you're still seeing this issue?

**Comment by emrahcom** [comment]
Hi Robert,

I applied the patch. The issue disappeared. it's OK now

thanks
emrah

**Comment by p0pr0ck5** [comment]
Great, closing this, and I will likely tag a new release today with this fix and a few other small feature additions. Thanks!
