### ISSUE TITLE
Lua entry thread aborted

### ISSUE THREAD

**Issue by sunny137** [p0pr0ck5/lua-resty-waf#140]
Just got resty waf working with config as shown in synposis but in SIMULATE mode. Trying to exercise rules with requests which contain malicious chars. I see that Lua thread aborts. What am I missing ?

2016/04/14 00:01:20 [error] 11249#0: *1 lua entry thread aborted: runtime error: ...sty-1.9.7.4/install/lualib/lua-resty-waf/inc/load_ac.lua:75: attempt to call upvalue 'ac_create' (a nil value)
stack traceback:
coroutine 0:
	...sty-1.9.7.4/install/lualib/lua-resty-waf/inc/load_ac.lua: in function 'create_ac'
	...y-1.9.7.4/install/lualib/lua-resty-waf/lib/operators.lua:222: in function <...y-1.9.7.4/install/lualib/lua-resty-waf/lib/operators.lua:215>
	...s/openresty-1.9.7.4/install/lualib/lua-resty-waf/waf.lua:268: in function '_process_rule'
	...s/openresty-1.9.7.4/install/lualib/lua-resty-waf/waf.lua:462: in function 'exec'
	access_by_lua(nginx.conf:57):10: in function <access_by_lua(nginx.conf:57):1>, client: 127.0.0.1, server: localhost, request: "GET /abcd?1=1 HTTP/1.1", host: "localhost"

==> nginx/logs/access.log <==
127.0.0.1 - - [14/Apr/2016:00:01:20 +0530] "GET /abcd?1=1 HTTP/1.1" 500 198 "-" "curl/7.43.0"

**Comment by sunny137** [comment]
Happens for legit requests too.



2016/04/14 00:16:08 [error] 11878#0: *10 lua entry thread aborted: runtime error: ...sty-1.9.7.4/install/lualib/lua-resty-waf/inc/load_ac.lua:75: attempt to call upvalue 'ac_create' (a nil value)
stack traceback:
coroutine 0:
	...sty-1.9.7.4/install/lualib/lua-resty-waf/inc/load_ac.lua: in function 'create_ac'
	...y-1.9.7.4/install/lualib/lua-resty-waf/lib/operators.lua:222: in function <...y-1.9.7.4/install/lualib/lua-resty-waf/lib/operators.lua:215>
	...s/openresty-1.9.7.4/install/lualib/lua-resty-waf/waf.lua:268: in function '_process_rule'
	...s/openresty-1.9.7.4/install/lualib/lua-resty-waf/waf.lua:462: in function 'exec'
	access_by_lua(nginx.conf:78):10: in function <access_by_lua(nginx.conf:78):1>, client: ::1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2016/04/14 00:16:08 [error] 11878#0: *11 lua entry thread aborted: runtime error: ...sty-1.9.7.4/install/lualib/lua-resty-waf/inc/load_ac.lua:75: attempt to call upvalue 'ac_create' (a nil value)
stack traceback:
coroutine 0:
	...sty-1.9.7.4/install/lualib/lua-resty-waf/inc/load_ac.lua: in function 'create_ac'
	...y-1.9.7.4/install/lualib/lua-resty-waf/lib/operators.lua:222: in function <...y-1.9.7.4/install/lualib/lua-resty-waf/lib/operators.lua:215>
	...s/openresty-1.9.7.4/install/lualib/lua-resty-waf/waf.lua:268: in function '_process_rule'
	...s/openresty-1.9.7.4/install/lualib/lua-resty-waf/waf.lua:462: in function 'exec'
	access_by_lua(nginx.conf:78):10: in function <access_by_lua(nginx.conf:78):1>, client: ::1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"

**Comment by sunny137** [comment]
Here is the entire nginx.conf, apologies if this is something really dumb. I am new to the whole thing, just moving from Apache to nginx. 

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;


    sendfile        on;
    keepalive_timeout  65;

    # include lua_resty_waf in the appropriate paths
    lua_package_path '/home/sunny/projects/sources/openresty-1.9.7.4/install/lualib/lua-resty-waf/?.lua;;';
    lua_package_cpath '/home/sunny/projects/sources/openresty-1.9.7.4/install/lualib/lua-resty-waf/?.lua;;';

    init_by_lua '
    -- use resty.core for performance improvement, see the status note above
    require "resty.core"

    -- require the base module
    local lua_resty_waf = require "waf"

    -- define options that will be inherited across all scopes
    lua_resty_waf.default_option("debug", true)

    -- perform some preloading and optimization
    lua_resty_waf.init()
  ';

server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;

        proxy_read_timeout                  1800s;
    proxy_set_header            Host $http_host;
    proxy_set_header            X-Real-IP $remote_addr;
    proxy_set_header            X-Forwarded-Host $host;
    proxy_set_header            X-Forwarded-Server $host;
    proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_buffer_size                   128k;
    proxy_buffers                               4 256k;
    proxy_busy_buffers_size             256k;
    proxy_redirect              http://#proxy_redirect_ip#/ http://$host/;
    proxy_redirect              https://#proxy_redirect_ip#/ https://$host/;
        
        location / {
                proxy_read_timeout      1800s;
        proxy_pass              http://127.0.0.1:8082;
        access_by_lua '
                local lua_resty_waf = require "waf"

                local waf = lua_resty_waf:new()

                -- default options can be overridden
                waf:set_option("debug", false)

                -- run the firewall
                waf:exec()
 ';

        header_filter_by_lua '
            local lua_resty_waf = require "waf"

           -- note that options set in previous handlers (in the same scope)
           -- do not need to be set again
           local waf = lua_resty_waf:new()

           waf:exec()
           ';

            body_filter_by_lua '
                local lua_resty_waf = require "waf"

                local waf = lua_resty_waf:new()

                waf:exec()
            ';

            log_by_lua '
                local lua_resty_waf = require "waf"

                local waf = lua_resty_waf:new()

                -- write out any event log entries to the
                -- configured target, if applicable
                waf:write_log_events()
            ';
        }

        }
}

**Comment by p0pr0ck5** [comment]
Hey sunny,

I am wondering if this is a permissions issue when trying to load the Aho-Corasick shared object library. What are the permissions of the file `inc/libao.so`? And what do the permissions of your home directory look like? The nginx user needs read permissions to this, which means it will need read permissions for parent directories as well, so maybe walk through your directory tree and see if the nginx user can't read that file?

**Comment by sunny137** [comment]
You are right. Mea culpa. I messed perms while building docker. I am running as a different user.

**Comment by p0pr0ck5** [comment]
No worries, the upstream AC lib doesn't handle these failures gracefully. I'll look at patching upstream to make it more clear when there's an issue loading the lib.
