### ISSUE TITLE
Suggestion : Move waf specific config to a separate file

### ISSUE THREAD

**Issue by sunny137** [p0pr0ck5/lua-resty-waf#150]
I am trying to move waf specific config from nginx.conf to separate config files which can be included form nginx.conf. I think this is a trivial change to do but keeps things readable.

I think it is a good idea to provide these sample config files and a dummy nginx file which shows how to include these. I know this is a tiny change but these are things which matter when someone new tries out things.

Here is my first attempt:

 
    -    ## include lua_resty_waf in the appropriate paths
    -    lua_package_path '/usr/local/openresty/lualib/lua_resty_waf/?.lua;;';
    -    lua_package_cpath '/usr/local/openresty/lualib/lua_resty_waf/?.lua;;';
     
    -    init_by_lua '
    -        -- use resty.core for performance improvement, see the status note above
    -        require "resty.core"
    -
    -        -- require the base module
    -        local lua_resty_waf = require "waf"
    -
    -        -- define options that will be inherited across all scopes
    -        lua_resty_waf.default_option("debug", true)
    -        lua_resty_waf.default_option("mode", "SIMULATE")
    -
    -        -- perform some preloading and optimization
    -        lua_resty_waf.init()
    -    ';
    +   include 'waf_init.conf';
 
    -                access_by_lua '
    -
    -                    local lua_resty_waf = require "waf"
    -
    -                    local waf = lua_resty_waf:new()
    -
    -                    -- default options can be overridden
    -                    --waf:set_option("allow_unknown_content_types", true)
    -                    waf:set_option("event_log_verbosity", 4)
    -                    -- waf:set_option("score_threshold", 10)
    -                    waf:set_option("event_log_target", "file")
    -                    waf:set_option("event_log_target_path", "/var/log/nginx/alerts.log")
    -                    -- periodically flush the send buffer 
    -                    waf:set_option("event_log_periodic_flush", 10)
    -                    waf:set_option("event_log_ngx_vars", "host")
    -                    waf:set_option("event_log_request_arguments", true)
    -                    waf:set_option("event_log_request_body", true)
    -                    waf:set_option("event_log_request_headers", true)
    -
    -                    -- run the firewall
    -                    waf:exec()
    -                ';
    -
    -                header_filter_by_lua '
    -                    local lua_resty_waf = require "waf"
    -
    -                    -- note that options set in previous handlers (in the same scope)
    -                    -- do not need to be set again
    -                    local waf = lua_resty_waf:new()
    -
    -                    waf:exec()
    -                ';
    -
    -                body_filter_by_lua '
    -                    local lua_resty_waf = require "waf"
    -
    -                    local waf = lua_resty_waf:new()
    -
    -                    waf:exec()
    -                ';
    -
    -                log_by_lua '
    -                    local lua_resty_waf = require "waf"
    -
    -                    local waf = lua_resty_waf:new()
    -
    -                    -- write out any event log entries to the
    -                    -- configured target, if applicable
    -                    waf:write_log_events()
    -                ';
    -
    +                include 'waf_options.conf';

But there is something wrong with this. The includes interfere with other nginx options which follow. Essentially, something is not right about this way of including. My prox_pass settings which following last include does not have any effect. What am I missing?

**Comment by p0pr0ck5** [comment]
It seems like the https://github.com/openresty/lua-nginx-module#access_by_lua_file directive would be useful for you here. This is something provided by the Lua nginx module, and doesn't require any change in lua-resty-waf.

Without posting your entire config there's no way to know how includes or other config changes are breaking things :)

**Comment by sunny137** [comment]
Sorry, forgot to attach the files. Here they are. 



[nginx.conf.txt](https://github.com/p0pr0ck5/lua-resty-waf/files/234204/nginx.conf.txt)
[waf_access.lua.txt](https://github.com/p0pr0ck5/lua-resty-waf/files/234207/waf_access.lua.txt)
[waf_body.lua.txt](https://github.com/p0pr0ck5/lua-resty-waf/files/234206/waf_body.lua.txt)
[waf_header.lua.txt](https://github.com/p0pr0ck5/lua-resty-waf/files/234205/waf_header.lua.txt)
[waf_init.lua.txt](https://github.com/p0pr0ck5/lua-resty-waf/files/234208/waf_init.lua.txt)
[waf_log.lua.txt](https://github.com/p0pr0ck5/lua-resty-waf/files/234209/waf_log.lua.txt)

**Comment by p0pr0ck5** [comment]
Are you still having issues, given that this issue is closed? If so, posting an entire Nginx debug log (not just the lua-resty-waf debug log) would be useful, as this will show how Nginx is handling the request.

**Comment by sunny137** [comment]
Closed by mistake !

**Comment by p0pr0ck5** [comment]
Your include issue sounds like a problem with your Nginx config, not lua-resty-waf itself. Can you please describe the specific issue you're having as well as provide a full Nginx debug log.

**Comment by sunny137** [comment]
I agree this is not an issue with lua waf. This is most certainly an issue with the way I have configured nginx. The reason I posted it here is I was planning to do a pull request and commit these changes as separate waf specific files which can be included in nginx.conf. I will post the debug logs once I get access to my test vm in some time. Do you see anything wrong with the way I am segregating lua code to files?

**Comment by p0pr0ck5** [comment]
We won't be supporting adding configs through a separate file. Using `*_by_lua_file` directives is sufficient; anything else is just more bloat and unnecessary complexity.

Nothing particularly wrong jumps out at me but I'm not exactly sure what the problem is, so I don't have much to go on. Saying "it doesn't work" isn't helpful :)

**Comment by sunny137** [comment]
Sounds good ! Will debug and get post back here as required. Will mark this one as closed since this is not lua waf specific and its decided that we dont want to add a feature on these lines any time soon. Thanks for your help Robert, I dont want to keep this one around, I guess it is just distracting :)
