### ISSUE TITLE
Luarocks distribution

### ISSUE THREAD

**Issue by thefosk** [p0pr0ck5/lua-resty-waf#153]
We would like to create a [Kong](https://github.com/Mashape/kong) WAF plugin and leverage your library. Would it be possible to publish the library on Luarocks? That would make it easier to include it.

If not, we can find a work-around, but Luarocks would be our first choice.

**Comment by p0pr0ck5** [comment]
Yes, I can work on this. Shouldn't be too difficult. :)

**Comment by p0pr0ck5** [comment]
@thefosk I need to do a bit of re-organizing and renaming directory structures, right now making a rockspec is a headache because we distribute a shared object (that needs to change!) and rules as JSON files (which the builtin Luarocks backend won't handle). I should probably write a Makefile for all this but I don't want to be a blocker for you; can you proceed with a workaround for now?

**Comment by shashiranjan84** [comment]
Hi @p0pr0ck5 ,

Actually I am working with @thefosk  on the WAF [plugin](https://getkong.org/plugins/) for Kong, I briefly went through your code and seems it would very easy to port it as a plugin on Kong as [Plugin](https://getkong.org/docs/0.8.x/plugin-development/) in Kong is just custom Lua code running on OpenResty. I would request you to look our Product once if you haven't done so, you going to like it. Would it a problem if we use most of your code to build the WAF plugin?

Thanks
Shashi

**Comment by p0pr0ck5** [comment]
@shashiranjan84 I would be happy if Kong used the entirety of lua-resty-waf for it's WAF plugin; I would ask that you do not simply copy-paste parts of the project.

**Comment by shashiranjan84** [comment]
@p0pr0ck5  it can't be integrated like that as a Plugin in Kong as Kong itself bundled with OpenResty.

**Comment by p0pr0ck5** [comment]
@shashiranjan84 can you clarify?

What exactly do you guys need from me at this point in the immediate future?

**Comment by shashiranjan84** [comment]
Currently just your permission to use ur code. I will port your code to
make it work with Kong.

**Comment by p0pr0ck5** [comment]
It's an open source project. Just remember to respect the license (GPLv3) :)

**Comment by p0pr0ck5** [comment]
Just an update, with the new work on restructuring the folder layouts and updating the Makefile, I should be able to accomplish this shortly (likely next week).

**Comment by p0pr0ck5** [comment]
This is up and live! @shashiranjan84 @thefosk 

http://luarocks.org/modules/p0pr0ck5/lua-resty-waf

Right now it points to the development branch; I will be tagging a formal v0.8 release next week and adjust this to point to master at that time.

**Comment by thefosk** [comment]
Great, thanks.
