### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by perfeyhe** [p0pr0ck5/lua-resty-waf#154]
Hi,I installed openresty,and then cloned  lua-resty-waf-master to /opt/openresty/lualib,but when I test: curl http://127.0.0.1, I got:curl: (52) Empty reply from server, the error log show this:
[error] 19312#0: *1 failed to run header_filter_by_lua*: /opt/openresty/lualib/resty/core/regex.lua:641: attempt to get length of local 'bit' (a number value)
stack traceback:
        /opt/openresty/lualib/resty/core/regex.lua:641: in function 'gsub'
        /opt/openresty/lualib/lua-resty-waf-master/lib/util.lua:121: in function 'parse_dynamic_value'
        /opt/openresty/lualib/lua-resty-waf-master/waf.lua:259: in function '_process_rule'
        /opt/openresty/lualib/lua-resty-waf-master/waf.lua:462: in function 'exec'

my install steps:
1. wget https://openresty.org/download/openresty-1.9.7.3.tar.gz
2. tar zxvf  #openresty-1.9.7.3.tar.gz
3. cd openresty-1.9.7.3
4. ./configure --prefix=/opt/openresty             
--with-pcre-jit             
--with-ipv6            
 --without-http_redis2_module             
--with-http_iconv_module            
 --with-http_postgres_module            
 -j2
5. make -j2
6. make install
7.cd ..
8. wget https://github.com/p0pr0ck5/lua-resty-waf/archive/master.zip
9. unzip master.zip
10. mv lua-resty-waf-master /opt/openresty/lualib/
11. export PATH=/opt/openresty/bin:/opt/openresty/nginx/sbin:$PATH

**Comment by p0pr0ck5** [comment]
You're see this because you're using an old version of OpenResty. Please see the following note in the Readme:

> lua-resty-waf is compatible with the master branch of lua-resty-core. The bundled version of lua-resty-core available in the current release of OpenResty (>= 1.9.7.4) is compatible with lua-resty-waf; versions bundled with older OpenResty bundles are not, so users wanting to leverage resty.core will either need to replace the local version with the one available from the GitHub project, or patch the module based off this commit.

So you have a few options:

- Use OpenResty 1.9.7.4
- Path lua-resty-core as noted above
- Don't use `resty.core`

Obviously the first option is recommended ;)

**Comment by perfeyhe** [comment]
I updated my  OpenResty to 1.9.7.4 ,it works.Thanks a lot
