### ISSUE TITLE
Check specific header

### ISSUE THREAD

**Issue by shinji62** [p0pr0ck5/lua-resty-waf#155]
Hi,

This lib is very usefull, now I am trying to make a reverse proxy /  transparent proxy doing WAF base on some header.

Basically the request URI will be in "X-CF-Forwarded-Url", how can I scan it ?

```lua
local headers = ngx.req.get_headers()
local cf_header_sign = headers["X-CF-Proxy-Signature"] 
local cf_header_metadata = headers["X-CF-Proxy-Metadata"] 
local cf_header_x_forwarded = headers["X-CF-Forwarded-Url"] 

if not cf_header_metadata or not cf_header_x_forwarded or not cf_header_sign  then
    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
end


-- WAF firewall rule
local lua_resty_waf = require "waf"
local waf = lua_resty_waf:new()

-- default options can be overridden
waf:set_option("debug", true)
-- run the firewall


ngx.var.forwarded_url = cf_header_x_forwarded
waf:exec()

```

Thanks

**Comment by p0pr0ck5** [comment]
I'm not sure exactly what you're trying to accomplish? What do you mean "scan it"?

**Comment by shinji62** [comment]
My question do you check any header ?

**Comment by p0pr0ck5** [comment]
I do not understand what you're asking. Are you asking how to use lua-resty-waf to check the value of a specific header? If so, you should write an appropriate rule using ModSecurity, then use the existing translation script at `tools/modsec2lua-resty-waf.pl` to translate.

Please also consider using a translator so we don't waste time not understanding each other :)

**Comment by shinji62** [comment]
wow that's rude ...
Maybe I misunderstood your script :)

Anyway thanks for the support !

**Comment by p0pr0ck5** [comment]
It's not rude to say I don't understand you. :) If you have a specific question, please feel free to let me know!
