### ISSUE TITLE
NGINX crashes due to header_filter_by_lua userdata length overflow

### ISSUE THREAD

**Issue by krugar100** [p0pr0ck5/lua-resty-waf#161]
While testing nginx with lua_resty_waf using some pentesting tools, nginx worker crashes with the following message :
2016/06/12 12:27:50 [error] 450#0: *34405 failed to run header_filter_by_lua*: userdata length overflow
stack traceback:
        [C]: in function 'get_headers'
        /usr/local/openresty/lualib/lua_resty_waf/lib/lookup.lua:49: in function </usr/local/openresty/lualib/lua_resty_waf/lib/lookup.lua:48>
        /usr/local/openresty/lualib/lua_resty_waf/waf.lua:419: in function 'exec'

Here's the syslog snapshot :
Jun 12 12:27:16 ip-*** kernel: [78993.003708] nginx[13933]: segfault at 8 ip 000000000041f0f0 sp 00007ffec8773b48 error 4 in nginx[400000+112000]
Jun 12 12:27:17 ip-*** kernel: [78993.345583] nginx[13932]: segfault at 0 ip 000000000041f0f0 sp 00007ffec8773ba8 error 4 in nginx[400000+112000]

I use openresty 1.9.7.4.

**Comment by p0pr0ck5** [comment]
Hi, as noted in https://github.com/openresty/lua-nginx-module/issues/797, this looks likely to be a bug within the ngx_lua module, not lua-resty-waf. Also for future note, syslog entries are worthless, we need full debug info and a core dump for issues such as these (https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#core-dump).

Closing this as wontfix, please follow the above lua-nginx-module bug.
