### ISSUE TITLE
No data writes to error.log

### ISSUE THREAD

**Issue by atktgs** [p0pr0ck5/lua-resty-waf#172]
I have added the following options to the config file, hoping to see some additional info from error.log but nothing shows up. Any additional config entries needed?

`...
                waf:set_option("debug_log_level", ngx.DEBUG)
                waf:set_option("event_log_altered_only", false)
                waf:set_option("event_log_request_arguments", true)
                waf:set_option("event_log_request_body", true)
                waf:set_option("event_log_verbosity", 4)
...`

**Comment by p0pr0ck5** [comment]
Have you set:

```waf:set_option("debug", true)```

**Comment by p0pr0ck5** [comment]
Closing after no response
