### ISSUE TITLE
modsec2lua fails

### ISSUE THREAD

**Issue by georgiopandarez** [p0pr0ck5/lua-resty-waf#173]
It complains there is more tokens with this rule:

SecRule "ARGS:overlay_type" "@pm ../ ..\\"                                                                                                                

Looks like there is an issue with the tokenization regex and the \\

**Comment by p0pr0ck5** [comment]
This is because the backslash at the end of your pattern is escaping the operator + pattern terminator. If you reverse the elements in your pattern it translates just fine:

```
poprocks@soter:~/code/Lua/lua-resty-waf$ echo 'SecRule "ARGS:overlay_type" "@pm ..\ ../" "id:'12345',phase:2,deny"' | tools/modsec2lua-resty-waf.pl -P
{
   "header_filter" : [],
   "access" : [
      {
         "action" : "DENY",
         "operator" : "PM",
         "pattern" : [
            "..\\",
            "../"
         ],
         "id" : "12345",
         "vars" : [
            {
               "type" : "REQUEST_ARGS",
               "parse" : {
                  "specific" : "overlay_type"
               }
            }
         ]
      }
   ],
   "body_filter" : []
}
```

That being said, I do think we could make some improvements to the quoted string regex.

**Comment by p0pr0ck5** [comment]
Patch for better quoted string regex forthcoming, however, not associated with the scope of this issue (which was discussed above).
