### ISSUE TITLE
multipart/form-data format should be '\r\n' instead of '\n'

### ISSUE THREAD

**Issue by perfgao** [p0pr0ck5/lua-resty-waf#192]
Hi,
When I use this request module to upload file, I find that the result is wrong.
the request Content-Type is multipart/form-data.
I noticed that the right format should be '\r\n' instead of '\n'.

`		while true do
			local typ, res, err = form:read()
			if not typ then
				logger.fatal_fail("failed to stream request body: " .. err)
			end
			
			if (typ == "header") then
				chunk = res[3] -- form:read() returns { key, value, line } here
				ngx.req.append_body("\n" .. chunk)
			elseif (typ == "body") then
				chunk = res
				if (lasttype == "header") then
					ngx.req.append_body("\n\n")
				end
				ngx.req.append_body(chunk)
			elseif (typ == "part_end") then
				ngx.req.append_body("\n--" .. form.boundary)
			elseif (typ == "eof") then
				ngx.req.append_body("--\n")
				break
			end
			
			lasttype = typ
		end`

Most textual Internet protocols (including HTTP, SMTP, FTP, IRC, and many others) mandate the use of ASCII CR+LF ('\r\n', 0x0D 0x0A) on the protocol level.

**Comment by p0pr0ck5** [comment]
Hi!

Thanks for the report! Will you consider submitting a patch (and a test for this case)? Request body handling does need some cleanup but I'm afraid I won't have time to work on it for at least several weeks.

**Comment by perfgao** [comment]
Hi!

OK, I will submit the relevant code in my spare time.

**Comment by p0pr0ck5** [comment]
Hi,

Since this was a relatively simply fix I went ahead and pushed the patch so I can tag a new release next week. Thanks for the report, I will credit you in the changelog :)
