### ISSUE TITLE
[Performance]

### ISSUE THREAD

**Issue by detailyang** [p0pr0ck5/lua-resty-waf#196]
i take notice of your README as the following:

>process transactions in roughly 300-500 microseconds per request

do you have more highly persuasive evidence (charts is better) to show us:)

**Comment by p0pr0ck5** [comment]
I did some regular flame graph work as early development was ongoing. See https://github.com/p0pr0ck5/lua-resty-waf/issues/8. Feel free to run your own tests using the ngx systemtap toolkit :)

**Comment by p0pr0ck5** [comment]
(also feel free to look at the occasional blog posts at https://www.cryptobells.com/tag/lua-resty-waf/)
