### ISSUE TITLE
SSL_Write Failed

### ISSUE THREAD

**Issue by bbates100** [p0pr0ck5/lua-resty-waf#203]
Hi,

Been trying to send logs to my remote server via this option **waf:set_option("event_log_target", "socket")** . However, sometimes I get this error message of: **SSL_Write() failed (SSL:) (32: Broken pipe), context: ngx.timer, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:443**

Any advice, in where should I start looking?
Thanks

**Comment by p0pr0ck5** [comment]
Hi,

Socket logging uses the [lua-resty-socket-logger](https://github.com/cloudflare/lua-resty-logger-socket) library to ship out log data. By default, the TCP connections used are kept in a keepalive pool with infinite timeout; if I had to make a blind guess, it sounds like the receiving end is closing the connection without letting the sender know? Sounds like you may want to open up an issue with the upstream library though. A few things of note:

- Anything in your remote end's error logs?
- Can you reproduce this behavior with just lua-resty-logger-socket and your remote SSL connection? Have a look at `lib/resty/waf/log.lua` for how we implement lua-resty-logger-socket, it's pretty simple.
- Does you have similar issues with connections dropped when using a plaintext connection?

Like I said, probably best to open a bug with the upstream lib maintainers, with as many details as possible. I'll leave this issue open for a while for reference.

**Comment by bbates100** [comment]
You were right. Thanks for the tip. 
It has something to do with the receiving end not responding accordingly.
Closing this ticket.

**Comment by p0pr0ck5** [comment]
Great, glad to hear there was a solution for you.

Mind sharing any details? It might make future searches for similar issues more useful.
