### ISSUE TITLE
storage_backend with redis

### ISSUE THREAD

**Issue by gocachebr** [p0pr0ck5/lua-resty-waf#213]
I dont see any interaction with the redis after being made requests... and there are no errors in the log. Even using the "monitor" I see no interaction.

Am I doing something wrong?

tcp        0      0 127.0.0.1:6379              0.0.0.0:*                   LISTEN      16151/redis-server 

**config redis**
...
lua_resty_waf.default_option("event_log_periodic_flush", 5)
...
waf:set_option("storage_backend", "redis")
waf:set_option("storage_host", "127.0.0.1")
waf:set_option("storage_port", 6379)
...

**log:**
2016/09/19 13:46:13 [error] 16506#16506: *24 [lua] log.lua:12: log(): [e1cd1c1f23ab5657d28e] Persisting storage type redis

**event_log_target:file**
{"id":"e1cd1c1f23ab5657d28e","client":"------","timestamp":1474307173,"method":"HEAD","uri":"\/alert=","ngx":{"host":"------","request_id":"036115949d850d409c0162bc526a0989"},"request_headers":{"host":"------","accept":"*\/*"},"uri_args":{"1232------1":true},"alerts":[{"msg":"No valid User-Agent header","id":21006,"action":"SCORE","opts":{}},{"match":2,"logdata":2,"id":99001,"action":"DENY","msg":"Request score greater than score threshold","opts":{"parsepattern":true}},{"match":2,"logdata":2,"id":99002,"action":"DENY","msg":"Request score greater than score threshold","opts":{"parsepattern":true}}]}

**Comment by p0pr0ck5** [comment]
Do you have any rules that write to persistent storage (e.g., using the `IP` collection)? If not, you will not see any data written to redis. `storage_backend` defines the engine to use for storing persistent data, not audit log data.

**Comment by gocachebr** [comment]
Thanks for reply!! And congratulations on the project.
