### ISSUE TITLE
Unable to run unittests

### ISSUE THREAD

**Issue by mtourne** [p0pr0ck5/lua-resty-waf#216]
Trying to run the tests, with the latest test-nginx library just to be sure.

I run into what looks like very trivial errors (unable to find resty.waf.actions).

I'm not super familiar with the Nginx::Test lib and your help would be greatly appreciated!

```
$ prove -I$HOME/Dev/test-nginx/lib t/unit/actions/disruptive/01_accept.t

t/unit/actions/disruptive/01_accept.t .. 1/24
#   Failed test 'TEST 1: ACCEPT exits the phase with ngx.OK - status code ok'
#   at /Users/mtourne/Dev/test-nginx/lib/Test/Nginx/Socket.pm line 882.
#          got: '500'
#     expected: '200'

#   Failed test 'TEST 1: ACCEPT exits the phase with ngx.OK - pattern "Rule action was ACCEPT, so ending this phase with ngx.OK" should match a line in error.log (req 0)'
#   at /Users/mtourne/Dev/test-nginx/lib/Test/Nginx/Socket.pm line 1106.

#   Failed test 'TEST 1: ACCEPT exits the phase with ngx.OK - pattern "[error]" should not match any line in error.log but matches line "2016/09/23 13:43:48 [error] 56188\#0: *1 lua entry thread aborted: runtime error: access_by_lua(nginx.conf:54):2: module 'resty.waf.actions' not found:" (req 0)'
#   at /Users/mtourne/Dev/test-nginx/lib/Test/Nginx/Socket.pm line 1161.

#   Failed test 'TEST 1: ACCEPT exits the phase with ngx.OK - status code ok'
#   at /Users/mtourne/Dev/test-nginx/lib/Test/Nginx/Socket.pm line 882.
#          got: '500'
#     expected: '200'
```

**Comment by p0pr0ck5** [comment]
Right now all the tests look in the default lua_package_path for the lua-resty-waf libs. So lua-resty-waf needs to be built and installed for tests to run properly. This is pretty simple with the Makefile:

`make && make install`

Btw, there's also a `make test` target that will run all the tests with the appropriate harness (by defining `PATH` as noted in http://search.cpan.org/~agent/Test-Nginx-0.24/lib/Test/Nginx/Socket.pm#DESCRIPTION. And yes, in the future I'll change this such that tests reference the local lua-resty-waf source instead of looking for a system lib.

**Comment by mtourne** [comment]
Thank you, I see to be able to run most of the unittests now, except for the ones below.

Also it takes a bit of hacking around to compile on mac os. I'm debating between fixing libsqlinjection Makefile upstream, or using this line instead which has mac os specifics, but requires swig to work : 
```
libinjection:
	cd libinjection/lua/ && make && cp $(LIB_INJECT) ../../lib/
```

=== Test errors ===
```
./t/unit/actions/disruptive/07_drop.t ........... 2/27
#   Failed test 'TEST 1: DROP exits the phase with ngx.HTTP_CLOSE - pattern "lua exit with code 444" should match a line in error.log (req 0)'
#   at /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Test/Nginx/Socket.pm line 1102.

#   Failed test 'TEST 1: DROP exits the phase with ngx.HTTP_CLOSE - pattern "lua exit with code 444" should match a line in error.log (req 1)'
#   at /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Test/Nginx/Socket.pm line 1102.

#   Failed test 'TEST 1: DROP exits the phase with ngx.HTTP_CLOSE - pattern "lua exit with code 444" should match a line in error.log (req 2)'
#   at /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/Test/Nginx/Socket.pm line 1102.
# Looks like you failed 3 tests of 27.
```

**Comment by p0pr0ck5** [comment]
Thanks for the upstream patch, we'll integrate it once it's accepted.

For the failing test, can you paste the contents of `t/servroot/conf/nginx.conf` after running that test? Odd that only one test in that file is failing. Did you compile your OpenResty bundle with `--with-debug`?

**Comment by p0pr0ck5** [comment]
Yep, that's it. I'll adjust that particular test so it doesn't rely on OpenResty built with debug.

Thanks for helping flesh out the testing harness, this is really useful work to have someone else take a crack!

**Comment by p0pr0ck5** [comment]
@mtourne going to close this bug, if you still have issues running tests please let me know!

**Comment by mtourne** [comment]
Unfortunately I have a feeling the upstream PR will never get merged, which makes the install process difficult on mac os. Wish I could do something about that ..

**Comment by p0pr0ck5** [comment]
client9 is busy. poke him every few weeks and he may respond.
