### ISSUE TITLE
Response body inspection not working while using nginx as reverse proxy

### ISSUE THREAD

**Issue by fuckingbaidu** [p0pr0ck5/lua-resty-waf#219]
here's my nginx config:
`    

	server {
		listen          80;
		server_name     localhost;

		location / {
		proxy_pass http://x.x.x.x/;
			access_by_lua ' 
				local lua_resty_waf = require "waf"
				local waf = lua_resty_waf:new()

				waf:set_option("event_log_target", "file")
				waf:set_option("event_log_target_path", "/var/log/waf/event.log")
				waf:set_option("event_log_verbosity", 4)
				waf:set_option("event_log_periodic_flush", 1)
				waf:set_option("event_log_request_arguments", true)
				waf:set_option("event_log_request_body", true)
				waf:set_option("event_log_request_headers", true)
				-- waf:set_option("deny_status", ngx.HTTP_NOT_ALLOWED) 
				waf:exec()
            ';

			header_filter_by_lua '
				local lua_resty_waf = require "waf"
				local waf = lua_resty_waf:new()
				waf:exec()
			';

			body_filter_by_lua '
				local lua_resty_waf = require "waf"
				local waf = lua_resty_waf:new()
				waf:exec()
			';

			log_by_lua '
				local lua_resty_waf = require "waf"
				local waf = lua_resty_waf:new()
				waf:write_log_events()
			';
		}
	}`

a simple custom rule inspecting phpinfo:
`# cat /data/openresty/lualib/rules/90000_custom.json
{
   "access" : {},
   "body_filter" : [
      {
	 "actions" : {
            "disrupt" : "DENY"
         },
         "id" : 90050,
         "msg" : "phpinfo detection",
         "operator" : "STR_CONTAINS",
         "pattern" : "phpinfo",
         "vars" : [
            {
               "type" : "RESPONSE_BODY"
            }
         ]
      }
   ],
   "header_filter" : {}
}`

When I comment the proxy_pass config,rule 90050 works while visiting a local html file including the string "phpinfo".
Then uncomment the proxy_pass config,rule 90050 does not work
Both response content types are text/html
Any ideals?Is this situation unsupported?

**Comment by fuckingbaidu** [comment]
And there's another problem:error happens in body_filter phase handling
Same config as above(comment the proxy_pass section)

When I visit a local html file containing the word "phpinfo",error happens:
`2016/09/27 10:27:52 [info] 4573#0: *1782 [lua] log.lua:12: log(): [a36001d5fca035f649ea] Rule action was DENY, so telling nginx to quit while sending response to client, client: 192.168.x.x, server: x.x.x.x, request: "GET /test.html HTTP/1.1", host: "x.x.x.x"
2016/09/27 10:27:52 [error] 4573#0: *1782 failed to run body_filter_by_lua*: /data/openresty/lualib/resty/waf/actions.lua:28: API disabled in the context of body_filter_by_lua*
stack traceback:
	[C]: in function 'exit'
	/data/openresty/lualib/resty/waf/actions.lua:28: in function </data/openresty/lualib/resty/waf/actions.lua:25>
	/data/openresty/lualib/resty/waf.lua:156: in function '_rule_action'
	/data/openresty/lualib/resty/waf.lua:304: in function '_process_rule'
	/data/openresty/lualib/resty/waf.lua:481: in function 'exec'
	body_filter_by_lua:4: in function <body_filter_by_lua:1> while sending response to client, client: 192.168.x.x, server: x.x.x.x, request: "GET /test.html HTTP/1.1", host: "x.x.x.x"
2016/09/27 10:27:52 [error] 4573#0: *1782 failed to run body_filter_by_lua*: /data/openresty/lualib/resty/waf/actions.lua:28: API disabled in the context of body_filter_by_lua*
`

**Comment by p0pr0ck5** [comment]
It's a known limitation of Nginx/OpenResty that response data cannot be modified once request headers have been sent. So trying to DENY a request in the body_filter phase doesn't make sense. There are several other actions (such as sleep) that also cannot execute in certain phases. This limitation does need to be better documented, I just haven't had time for that lately.

I suspect that something else is going on when you have reverse proxy enabled, and would encourage you to dig deeply into the logs to figure out what's going on, if you're interested. It's not something we'll ever be able to fix due to the streaming nature of Nginx responses.
