### ISSUE TITLE
False positive hits

### ISSUE THREAD

**Issue by kiuka** [p0pr0ck5/lua-resty-waf#221]
Hi,

First of all, thank you for your work. I've tried lua-resty-waf using the suggested config, and I experienced that it reject a lot of requests but most of them are false positive hit.

For example a trivial one: it reject google cookies

`{"timestamp":1475162526,"method":"GET","uri":"\/a-halott-csecsemoknek-ad-vegtisztesseget\/","id":"cda2523c9574778a2a96","uri_args":{},"client":"...","alerts":[{"match":{"0":"=facebook.com|utmccn=(referral)|utmcmd=referral|","1":"|"},"id":41014,"action":"SCORE","msg":"SQL Injection character anomaly - COOKIES","opts":{"transform":"uri_decode"}},{"match":{"0":"=facebook.com|utmccn=(referral)|","1":"|"},"id":41015,"action":"SCORE","msg":"SQL Injection character anomaly - ARGS","opts":{"transform":"uri_decode"}},{"match":8,"logdata":8,"id":99001,"action":"DENY","msg":"Request score greater than score threshold","opts":{"parsepattern":true}},{"match":8,"logdata":8,"id":99002,"action":"DENY","msg":"Request score greater than score threshold","opts":{"parsepattern":true}},{"match":8,"logdata":8,"id":99003,"msg":"Request score greater than score threshold","opts":{"parsepattern":true}}]}
`

Actually I've been using it for 10 minutes before disabled it, and all of the matches were false positive.

Is there anything I can do to avoid these matches, or can I help your works by sending these false positive matches to you?

Thanks in advance.

**Comment by p0pr0ck5** [comment]
Hi,

Thanks for checking out the project! The rules distributed with lua-resty-waf come from the OWASP CRS (https://github.com/SpiderLabs/owasp-modsecurity-crs). If you're having trouble with false positives I would suggest ensuring that you have the same problem with ModSecurity itself, and then disable the rules that are causing false positives for you via the `ignore_rule` or `ignore_ruleset` options.

It's worth noting that we're in the process of translating the new CRS v3 rules for inclusion with this project, which should be available around the end of October.
