### ISSUE TITLE
ignore_ruleset doesnt work

### ISSUE THREAD

**Issue by kiuka** [p0pr0ck5/lua-resty-waf#222]
Hello again:)

Referring to https://github.com/p0pr0ck5/lua-resty-waf/issues/221 I tried to ignore the rules that cause false positive hits.

The ignore_rule option works fine, but when I try to ignore an entire ruleset, it does nothing. I tried it with table and with pure number, either worked.

My access_by_lua block config is the following:

`
            local lua_resty_waf = require "waf"

            local waf = lua_resty_waf:new()

            -- default options can be overridden
            waf:set_option("debug", true)
            waf:set_option("event_log_target", "file")
            waf:set_option("event_log_target_path", "/var/log/nginx/waf.log")

            -- Declare the log level
            waf:set_option("debug_log_level", ngx.DEBUG)
            waf:set_option("event_log_altered_only", false)
            waf:set_option("event_log_request_arguments", true)
            waf:set_option("event_log_request_body", true)
            waf:set_option("event_log_verbosity", 4)
            waf:set_option("ignore_rule", { 21003, 21006, 21009, 41001, 40002, 41003, 41004, 41005, 41014, 41015, 41017, 41018, 41032, 41033, 41036 })
            waf:set_option("ignore_ruleset", { 42000, 99000 })

            -- run the firewall
            waf:exec()
`
`

**Comment by p0pr0ck5** [comment]
Hi,

The documentation for `ignore_ruleset` was out of date; the rulesets were renamed several versions ago, and the docs were not included to reflect this. I'll be updating the readme shortly. You can call ignore_ruleset as such to ignore those rules:

`waf:set_option("ignore_ruleset", "42000_xss")`

**Comment by p0pr0ck5** [comment]
Docs are now updated on the master branch.

**Comment by kiuka** [comment]
thank you!
