### ISSUE TITLE
Skip waf based on IP 

### ISSUE THREAD

**Issue by urosgruber** [p0pr0ck5/lua-resty-waf#233]
This is more of a question than a bug report. Is there any other way to skip WAS rules for a specific IP other than using custom rules? I have a list of IPs per host and would like to skip waf in case host is accessed from specific IP address.

**Comment by p0pr0ck5** [comment]
If you want to avoid skipping _all_ execution for a given IP or CIDR range (or really any arbitrary logic), you can simply bake that into your *_by_lua phase handlers. For example:

```lua
access_by_lua '
local w = require "resty.waf"
local waf = w:new()

local skip = ngx.var.remote_addr == "192.168.1.1" -- or whatever logic you want

if (not skip) then
waf:exec()
end
';
```

Again, you have the freedom to bake in your own logic based on your business needs as part of your phase handler config, no need for separate work inside lua-resty-waf for that. There is no way to skip execution of only _some_ rules of lua-resty-waf, outside of rule logic; that seems like unnecessary feature bloat and won't be implemented.

Well, we used to have a few rules that allowed for whitelist/blacklist, but that seemed like overkill when it could be done in the Nginx config directly ;) Let me know if this helps, or you still need clarification on anything. thanks

**Comment by urosgruber** [comment]
I think this could work just fine. I guess this need to be done in all phases, right?

**Comment by p0pr0ck5** [comment]
Correct, everywhere that you're calling `waf:exec()`.

**Comment by p0pr0ck5** [comment]
Closing this to keep the issues page clean, but let me know if I can answer any other questions.
