### ISSUE TITLE
add custom rules

### ISSUE THREAD

**Issue by fabregas4you** [p0pr0ck5/lua-resty-waf#234]
Hi.

Not issues, please help me about How to add custom rules looks like "~/rules/9x000_custom.json".
The  repos default rules are just fine , so there default rules uses "common". But we add to some
cutom rules for DENY particular "User-Agent" , "referer" , "request headers" or so on.

If is there any documets or material, please tell me the location ?
Thank you.

**Comment by p0pr0ck5** [comment]
Hi,

There is tooling in the `tools` directory to translate ModSecurity rulesets and create a new JSON files with the defined rules. So you will have to write your own rules with ModSecurity DSL and translate them for now.

In the future we may introduce our own DSL for creating new rules. But this is not a set plan. Let me know if I can help clarify anything.

**Comment by fabregas4you** [comment]
Thank you very much!
