### ISSUE TITLE
Compile on Official Nginx

### ISSUE THREAD

**Issue by smoghaddas** [p0pr0ck5/lua-resty-waf#237]
Dear all
when i trying to compile waf with official nginx 1.11.2, i got an error.
1- compile luajit 2.0.4
2- compile nginx with ngx_devel_kit, pcre 8.39, lua nginx module 0.10.6
​3!- compile lua-resty-waf : i got an error here... first of all i got about lua.h, because i dont have lua5.1 and i have luajit. after change lua-aho-corasick/Makefile to
            LUA_VERSION := 2.0
            PREFIX = /usr/local
            LUA_INCLUDE_DIR := $(PREFIX)/include/luajit-$(LUA_VERSION)
            SO_TARGET_DIR := $(PREFIX)/lib
            LUA_TARGET_DIR := $(PREFIX)/share/luajit/jit​

​      after this, i got error in "make install" .... in lua-resty-waf/Makefile​
these addrress are not exist: 
    OPENRESTY_PREFIX ?= /usr/local/openresty
    LUA_LIB_DIR ?= $(OPENRESTY_PREFIX)/lualib
because i dont have openresty...
and luajit data in
LUAJIT_LIB=/usr/local/lib
LUAJIT_INC=/usr/local/include/luajit-2.0
what can i do now about lua-resty-waf/Makefile​ to configure with official nginx ?

**Comment by p0pr0ck5** [comment]
Hi,

lua-resty-waf targets OpenResty specifically. Compilation with vanilla Nginx or custom distributions is unsupported at this time. Patches welcome for extending the Makefile, provided that the existing targets and results are unchanged for OpenResty users.

**Comment by ghost** [comment]
@sinamoghaddas Hi, have you successfully compiled lua-resty-waf with official nginx ?
Because I need to do it too and openresty isn't a solution due to a lot of modules
Thanks
