### ISSUE TITLE
Automatic IP Banning

### ISSUE THREAD

**Issue by rm3nchaca** [p0pr0ck5/lua-resty-waf#273]
Hi!
Is there a way to automatically deny an IP for a period of time, for example, after N malicious requests?
Thank you!

**Comment by p0pr0ck5** [comment]
You'll need to write or use existing ModSecurity rules for this. The OWASP rules, which this project supports, already have an example of this: https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-912-DOS-PROTECTION.conf

**Comment by rm3nchaca** [comment]
Thanks, I'll try that way.!
