### ISSUE TITLE
All regexes need to be case-insensitive

### ISSUE THREAD

**Issue by chupacabra007** [p0pr0ck5/lua-resty-waf#298]
I try to filter all XSS from [this](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet) list, using lua-resty-waf, but see that some requests are not filtered, because they have capital letters in them. For example, this type of request won't be filtered:

`http://localhost/test/?a=<A HREF="http://1113982867/">XSS</A>`

while this will be filtered

`http://localhost/test/?a=<a href="http://1113982867/">XSS</A>`

**Comment by p0pr0ck5** [comment]
Hi,

Apologies for the delayed response. Since regular expressions can be defined with the `(?i)` modifier, it is up to the rule author to write rules with respect to case sensitivity. Thank you!
