### ISSUE TITLE
jsdecode and cssdecode?

### ISSUE THREAD

**Issue by chenyoufu** [p0pr0ck5/lua-resty-waf#54]

**Comment by p0pr0ck5** [comment]
As you asking for these features to be added? I likely won't have time to develop this for a while. Patches welcome :)

**Comment by p0pr0ck5** [comment]
Closing this as this is a known limitation documented in https://github.com/p0pr0ck5/lua-resty-waf/wiki/Known-ModSecurity-Translation-Limitations, and we're not going to create individual bugs for each missing element.

**Comment by p0pr0ck5** [comment]
(marking this particular bug as wontfix due to its scope)
