### ISSUE TITLE
RBL support

### ISSUE THREAD

**Issue by p0pr0ck5** [p0pr0ck5/lua-resty-waf#73]

**Comment by hy05190134** [comment]
what's the mean of RBL?

**Comment by p0pr0ck5** [comment]
https://en.wikipedia.org/wiki/DNSBL

It is a method of performing IP reputation lookup

**Comment by hy05190134** [comment]
See a little, will RBL be designed for ip or uri?  whether or not to just lookup the DNS and get the blacklist  info?

**Comment by p0pr0ck5** [comment]
RBL is use to lookup a client IP. This would be similar to ModSecurity's @RBL operator (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#rbl)
